### ISSUE TITLE
Compile error on alpine

### ISSUE THREAD

**Issue by dongli** [thkukuk/libnsl#3]
Just do the normal installation procedures, but met the following error when make:
```
Making all in src
make[2]: Entering directory '/root/libnsl/src'
/bin/bash ../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I..  -I. -I/usr/include/tirpc  -DLOCALEDIR=\"/opt/libnsl/share/locale\"  -W -Wall -Wbad-function-cast -Wcast-align -Winline -Wnested-externs -Wshadow -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -D_REENTRANT=1 -g -O2 -MT yp_xdr.lo -MD -MP -MF .deps/yp_xdr.Tpo -c -o yp_xdr.lo yp_xdr.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -I. -I/usr/include/tirpc -DLOCALEDIR=\"/opt/libnsl/share/locale\" -W -Wall -Wbad-function-cast -Wcast-align -Winline -Wnested-externs -Wshadow -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -D_REENTRANT=1 -g -O2 -MT yp_xdr.lo -MD -MP -MF .deps/yp_xdr.Tpo -c yp_xdr.c  -fPIC -DPIC -o .libs/yp_xdr.o
In file included from ./rpcsvc/yp_prot.h:11:0,
                 from yp_xdr.c:42:
./rpcsvc/ypclnt.h:53:1: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'struct'
 struct ypall_callback
 ^~~~~~
./rpcsvc/ypclnt.h:61:12: warning: no previous prototype for 'yp_bind' [-Wmissing-prototypes]
 extern int yp_bind (const char *) __THROW;
            ^~~~~~~
./rpcsvc/ypclnt.h: In function 'yp_bind':
./rpcsvc/ypclnt.h:61:35: error: expected declaration specifiers before '__THROW'
 extern int yp_bind (const char *) __THROW;
                                   ^~~~~~~
./rpcsvc/ypclnt.h:62:38: error: expected '=', ',', ';', 'asm' or '__attribute__' before '__THROW'
 extern void yp_unbind (const char *) __THROW;
                                      ^~~~~~~
./rpcsvc/ypclnt.h:63:44: error: expected '=', ',', ';', 'asm' or '__attribute__' before '__THROW'
 extern int yp_get_default_domain (char **) __THROW;
                                            ^~~~~~~
./rpcsvc/ypclnt.h:65:35: error: expected '=', ',', ';', 'asm' or '__attribute__' before '__THROW'
        const int, char **, int *) __THROW;
                                   ^~~~~~~
./rpcsvc/ypclnt.h:67:31: error: expected '=', ',', ';', 'asm' or '__attribute__' before '__THROW'
        int *, char **, int *) __THROW;
                               ^~~~~~~
./rpcsvc/ypclnt.h:69:50: error: expected '=', ',', ';', 'asm' or '__attribute__' before '__THROW'
       const int, char **, int *, char **, int *) __THROW;
                                                  ^~~~~~~
```

**Comment by kopiro** [comment]
Any update here?

**Comment by thkukuk** [comment]
As written in the README, this is a replacement of the glibc libnsl. I don't think that alpine is using glibc, at least from the errors it doesn't look like.
So somebody has to port the code to whatever alpine is using or you have to wait until I have time to setup such a system and port myself.

**Comment by thkukuk** [comment]
Should compile now on alpine, too.

**Comment by Norgul** [comment]
It doesn't compile on my `3.7` version:

```
make  all-recursive
make[1]: Entering directory '/usr/local/instantclient_18_3/libnsl'
Making all in po
make[2]: Entering directory '/usr/local/instantclient_18_3/libnsl/po'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/usr/local/instantclient_18_3/libnsl/po'
Making all in src
make[2]: Entering directory '/usr/local/instantclient_18_3/libnsl/src'
/bin/bash ../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I..  -I.  -DLOCALEDIR=\"/usr/share/locale\"  -W -Wall -Wbad-function-cast -Wcast-align -Winline -Wnested-externs -Wshadow -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -D_REENTRANT=1 -g -O2 -MT yp_xdr.lo -MD -MP -MF .deps/yp_xdr.Tpo -c -o yp_xdr.lo yp_xdr.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -I. -DLOCALEDIR=\"/usr/share/locale\" -W -Wall -Wbad-function-cast -Wcast-align -Winline -Wnested-externs -Wshadow -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -D_REENTRANT=1 -g -O2 -MT yp_xdr.lo -MD -MP -MF .deps/yp_xdr.Tpo -c yp_xdr.c  -fPIC -DPIC -o .libs/yp_xdr.o
yp_xdr.c:41:23: fatal error: rpc/types.h: No such file or directory
 #include <rpc/types.h>
                       ^
compilation terminated.
make[2]: *** [Makefile:587: yp_xdr.lo] Error 1
make[2]: Leaving directory '/usr/local/instantclient_18_3/libnsl/src'
make[1]: *** [Makefile:487: all-recursive] Error 1
make[1]: Leaving directory '/usr/local/instantclient_18_3/libnsl'
make: *** [Makefile:396: all] Error 2
```

**Comment by thkukuk** [comment]
> It doesn't compile on my `3.7` version:

Then you should fix your development environment and install all missing packages, e.g. a rpc library. libnsl compiles fine on Alpine Linux.
